name: libKeyFinder

on:
  push:
  pull_request:

jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cmake fftw3-dev
    - name: build
      run: |
        mkdir build
        mkdir ~/libKeyFinder
        cmake -DCMAKE_INSTALL_PREFIX=~/libKeyFinder -S . -B build
        cmake --build build --target install
    - name: run tests
      run: build/tests/test
    - name: upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu build
        path: ~/libKeyFinder
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        brew install fftw
    - name: build
      run: |
        mkdir build
        mkdir ~/libKeyFinder
        cmake -DCMAKE_INSTALL_PREFIX=~/libKeyFinder -S . -B build
        cmake --build build --target install
    - name: run tests
      run: build/tests/test
    - name: upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS build
        path: ~/libKeyFinder
